[package]
name = "chakra"
version = "0.9.2"
edition = "2021"
description = "A WebAssembly Runtime"
license = "MIT"
authors = ["Kumar Anirudha <chakra@anirudha.dev>"]
repository = "https://github.com/anistark/chakra"
readme = "README.md"
keywords = ["wasm", "webassembly", "browser", "runtime", "cli"]
categories = ["command-line-utilities", "development-tools", "wasm"]
include = ["src/**", "assets/**", "Cargo.toml", "README.md", "LICENSE"]
documentation = "https://docs.rs/chakra"
rust-version = "1.70.0"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
tiny_http = "0.12"
webbrowser = "1.0.4"
notify = "5.1.0"
notify-debouncer-mini = "0.2.1"
thiserror = "1.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
dirs = "5.0"

[dev-dependencies]
tempfile = "3.8"

[[bin]]
name = "chakra"
